name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - run: sh tests/test.sh

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: shellcheck -s sh vv tests/test.sh

  homebrew:
    runs-on: macos-latest
    steps:
      - run: brew install geo4orce/tap/vv
      - run: brew test geo4orce/tap/vv
